### ISSUE TITLE
Android Settings

### ISSUE THREAD

**Issue by mikevanilla** [hvdwolf/Joying-RootAssistant#4]
Installing the android settings appears to work correctly but app crashes when attempting to open the default settings. I downloaded from the app from your app directly and did a reboot before attempting to open. I've now re-installed the default settings from your app and the main settings menu opens but if I attempt to open a sub-menu the settings app will crash.

**Comment by hvdwolf** [comment]
I released V1.3 with some modifications. See the [Releases](https://github.com/hvdwolf/Joying-RootAssistant/releases) page

**Comment by mikevanilla** [comment]
Just tried with new app version, downloaded the Android settings and second file. Rebooted when prompted. It appears to bring back submenus but I still don't see some standard Android settings like Bluetooth. It actually appears like the default joying settings but I can't remember all that was available or not to confirm this. The download URL for default joying settings might not be correct either, just set to Settings.apk.

**Comment by hvdwolf** [comment]
The Joying settings.apk has a dark-grey background. The standard android settings.apk has a white background with with green-blue (turqoise?) characters.

**Comment by mikevanilla** [comment]
It is default joying still. Dark grey.

**Comment by hvdwolf** [comment]
Did you really install the "Install standard Android Settings" option? I tested it this morning (of course) and switched a couple of times between this "Install standard Android Settings" and the "(Re)Install Joying Settings".
The android settings has not changed between 25 May and 07 July, only the joying settings.apk

**Comment by mikevanilla** [comment]
Yeah I tried twice for standard Android. It is weird though because submenus for default joying settings work. I only tried the Android standard settings APK and never the default joying setting from the new app. I'll try again to confirm

**Comment by mikevanilla** [comment]
I tried again and same thing, standard Android appears to be default joying settings. I've been trying to download the joying default to see if a switch between the two would make any difference but it doesn't appear to be downloading. The URL is simply 'Settings.apk' not sure if that is a mislabeled url but it's not showing the full github url as it did before.

**Comment by mikevanilla** [comment]
[JET-20170723.log.txt](https://github.com/hvdwolf/Joying-RootAssistant/files/1168325/JET-20170723.log.txt)

**Comment by hvdwolf** [comment]
I do not understand it at this moment. If I look at the log, the correct apk is installed together with the odex. It should work, but obviously doesn't.
23-Jul-2017 14:08:35 /system/priv-app/Settings/: 
-rw-r--r-- root root 20952963 2017-07-23 14:08 Settings.apk 
-rw------- root root 20952963 2017-07-23 14:08 Settings.apk.old 
drwxr-xr-x root root 2017-07-22 11:43 oat /system/priv-app/Settings//oat: 
drwxr-xr-x root root 2017-07-22 11:43 x86 /system/priv-app/Settings//oat/x86: 
-rw-r--r-- root root 6218220 2017-07-23 14:08 Settings.odex

The only strange thing is the double /. The script is not doing it, so I wonder where it comes from.

I did make some minor changes to the script by changing the order in which some copying takes place. It might help and maybe not. 
Please try/test:  https://drive.google.com/open?id=0B4J3kKZoV78-NW96M2IxQ1ptcUE

**Comment by mikevanilla** [comment]
Same result.
[JET-20170723.log.txt](https://github.com/hvdwolf/Joying-RootAssistant/files/1168403/JET-20170723.log.txt)

**Comment by hvdwolf** [comment]
I released a 1.4 version. I "put in" the 25 May and 07 July version of the Android Settings.apk version.
Please try and let me know.
Some others already replied it works for them.

**Comment by mikevanilla** [comment]
It just never downloads any Settings.apk files. I've tried a few times and it just hangs. Never gives an error or anything, I checked the logs and it shows that I select that option but then silence. I tried uninstalling and reinstalling. You said other users have had success so I guess it's not the URL, but since 1.3 I've noticed the full URL does not show on the download screen. I see the thread on XDA and I'm getting the same problem as a user there who eventually re-flashed the ROM and then had success. Not sure if I'm going to have a chance to do that today but it seems like the only success story I've read.

**Comment by WallyDoodlez** [comment]
I have the same issue. I used the setprop on the terminal to set port to 5555 and then I installed joying extra settings. I ran install original android settings and then rebooted and all settings apps are gone, and it seems like pressing the settings COG on the notification drop down does nothing.

When I attempted to install the original joying settings app, it just says "Downloading" and runs forever.
It seems like to me that there is no network activity? Is the .apk's stored on GitHub? As I know there is a major outage on GitHub as of now.

**Comment by hvdwolf** [comment]
This answer might not help you, but it is to reflect that the downloads really take place. (I know, the reply "it works for me, so it should work for you" is the most lame answer you can get as a user when it doesn't work for you. I only mention it because I can't reproduce your issue). 
I upgraded to the 07 July version and used my 1.4 version (after having rooted my unit).
I have both installed the standard Android settings as well as the Joying settings at least 4-5 times on 2 consecutive days.

Note though that most Joying apps are 1-2 MB in size while the Settings.apk is 20MB+. It does indeed take 10x as long before the download is finished. With a flaky, not so strong WiFi connection it might indeed take very long.

I also reveiced a notification from a user on XDA that it functions for him. Again: that does not solve it for you, but I simply don't know why it doesn't function for you. The only thing I can think of is the "weird" behavior of these 6.0.1 ROMs. With other mods it works for one and not for the next person. I assume it is here the same.

**Comment by criminalx** [comment]
I have a issue with the Android settings Download, i click it and saying downloading, but it never finish...

**Comment by hvdwolf** [comment]
If you use the1.5 version of my apk, there is quite some lgging taking place. The logging is written to /sdcard/JET-yyyymmdd.log

I (re)installed the joying settings.
The log is then:

```
05-aug.-2017 19:00:41 : Android or Joying Settings.apk selection "(Re)Install Joying Settings" for Android version: 6.0.1. With jetscript parameter: Settings Using download path: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/joying/20170629/ and trying to download: (Settings.apk)
05-aug.-2017 19:00:42 : Initialized the DownloadView screen
05-aug.-2017 19:00:42 : Downloading file: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/joying/20170629/Settings.apk ; And saving it as: /JET/Settings.apk
05-aug.-2017 19:00:59 : Finished dowloading the file(s).
05-aug.-2017 19:01:01 : Result parameter after Downloadview, needed to start jetscript: Settings
05-Aug-2017 19:01:01 : Start of jetscript.sh
05-Aug-2017 19:01:01 : Start of replacing the installed Settings.apk
05-Aug-2017 19:01:03

/system/priv-app/Settings/:
-rw-r--r-- root     root     22314964 2017-08-05 19:01 Settings.apk
-rw------- root     root     20952963 2017-08-05 19:01 Settings.apk.old
05-Aug-2017 19:01:03 : Ending jetscript.sh
05-aug.-2017 19:01:03 : RootExecAction (if any): "Settings"  and the output from the script (if any): 
```


I then installed the default android settings again:

```
05-aug.-2017 19:02:14 : Android or Joying Settings.apk selection "Install standard Android Settings" for Android version: 6.0.1. With jetscript parameter: Settings AOSP601 Using download path: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/android/20170629/ and trying to download: (Settings.apk Settings.odex)
05-aug.-2017 19:02:15 : Initialized the DownloadView screen
05-aug.-2017 19:02:15 : Downloading file: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/android/20170629/Settings.apk ; And saving it as: /JET/Settings.apk
05-aug.-2017 19:02:46 : Downloading file: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/android/20170629/Settings.odex ; And saving it as: /JET/Settings.odex
05-aug.-2017 19:02:54 : Finished dowloading the file(s).
05-aug.-2017 19:02:57 : Result parameter after Downloadview, needed to start jetscript: Settings
05-Aug-2017 19:02:57 : Start of jetscript.sh
05-Aug-2017 19:02:57 : Start of replacing the installed Settings.apk
05-Aug-2017 19:02:58
/system/priv-app/Settings/:
-rw-r--r-- root     root     20952963 2017-08-05 19:02 Settings.apk
-rw------- root     root     22314964 2017-08-05 19:02 Settings.apk.old
drwxr-xr-x root     root              2017-08-05 19:02 oat

/system/priv-app/Settings//oat:
drwxr-xr-x root     root              2017-08-05 19:02 x86

/system/priv-app/Settings//oat/x86:
-rw-r--r-- root     root      6218220 2017-08-05 19:02 Settings.odex
05-Aug-2017 19:02:59 : Ending jetscript.sh
05-aug.-2017 19:02:59 : RootExecAction (if any): "Settings AOSP601"  and the output from the script (if any): 
```


I use the rom build date instead of the release date. So 20170629 is the "07 July"  version.
You see in the joying one
```
05-aug.-2017 19:02:15 : Downloading file: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/android/20170629/Settings.apk
```

And in the android one:
```
05-aug.-2017 19:02:15 : Downloading file: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/android/20170629/Settings.apk ; And saving it as: /JET/Settings.apk
05-aug.-2017 19:02:46 : Downloading file: https://github.com/hvdwolf/Joying-RootAssistant/raw/apk/Settings/601/android/20170629/Settings.odex ; And saving it as: /JET/Settings.odex
```

Please check your log files for these lines. Please also try to copy & paste them into the local browser of your unit to see what it does.

**Comment by criminalx** [comment]
If i visit the link it start download,but from app no work ,this is the log

**Comment by criminalx** [comment]
06-ago.-2017 11:34:42 : Starting Joying Extra Tools
06-ago.-2017 11:34:42 : Color scheme set; Theme color: 4280391411 ; Layout color: 4294177779
06-ago.-2017 11:34:42 : Is jetscript copied to the /data/data/appinventor.ai_hvdwolf.Joying_Extra_Tools folder?: true
06-ago.-2017 11:34:42 : Apk version 1.5 running on Android 6.0.1 on Rom build version (ro.build.date=2017-06-15 20:44:28 Thursday)
06-ago.-2017 11:34:42 : Do network check
06-ago.-2017 11:34:42 : ip-address is: 172.20.10.2
06-ago.-2017 11:34:48 : Result from Textview: Accept
06-ago.-2017 11:34:48 : RootExecAction (if any): "get_persistent_state"  and the output from the script (if any): -1

06-ago.-2017 11:34:56 : Android or Joying Settings.apk selection "Install standard Android Settings" for Android version: 6.0.1. With jetscript parameter: Settings AOSP601 Using download path:  and trying to download: (Settings.apk Settings.odex)
06-ago.-2017 11:34:57 : Initialized the DownloadView screen
06-ago.-2017 11:34:57 : Downloading file: Settings.apk ; And saving it as: /JET/Settings.apk

**Comment by hvdwolf** [comment]
Your log mentions: `ro.build.date=2017-06-15 20:44:28 Thursday`

Wich ROM are you using? I only know the 25 May version with build date 2017-05-24, and the 7 July (or 5 July) version with build date 2017-06-29.
Can you give me a link to that ROM? 
Is it by any chance one of the 800x480 ROMs?

**Comment by hvdwolf** [comment]
@mikevanilla and @WallyDoodlez :
Which ROMs do you use? a 5.1.1 to 6.0.1 ROM, an 800x480 ROM?
Can you check the build date in the /system/build.prop (or send it to me)?

Until now I assumed all ROMs released on the same date, also had the same build date.
To make sure I downloaded the 5->6 800x480, the 6->6 800x480, the 5->6 1024x600 and the 6->6 1024x600 of July 7 (website), or July 5 (if you look at the zip)
These four ROMs all have the same build date `ro.build.date=2017-06-29 11:43:58 Thursday`

**Comment by criminalx** [comment]
Not sure how to check the rom, I think it is default I get this one a month ago: https://www.carjoying.de/android-6-0-car-autoradio/vw-android-6-0-car-stereo/new-digital-amplifier-built-in-car-autoradio-android-6-0-head-unit-music-system-with-very-good-sound-quality-for-vw-passat-jetta-glof-polo.html

**Comment by hvdwolf** [comment]
That doesn't help me. :)
If you open my app, the build.prop is copied to the /sdcard (and removed upon app closure).
With my app open, can you switch to google drive, dropbox, gmail or whatever you use and copy/share/mail that build.prop from the /sdcard?

I will program a small function in my app that allows you to share the build.prop and the logs, but that is not for now.

**Comment by criminalx** [comment]
Uploaded here
[build.zip](https://github.com/hvdwolf/Joying-RootAssistant/files/1203149/build.zip)

**Comment by hvdwolf** [comment]
Thank you.

Please try this version: https://drive.google.com/open?id=0B4J3kKZoV78-NW96M2IxQ1ptcUE

And while testing please also try the new share function from the top-left menu (triple horizontal bar), called "Share my build.prop and logs".
And please send it to me or share it or upload it.

**Comment by criminalx** [comment]
This one work fine, thanks mate. 
Sent the report to your mail

**Comment by mikevanilla** [comment]
[build.prop.txt](https://github.com/hvdwolf/Joying-RootAssistant/files/1203243/build.prop.txt)

**Comment by mikevanilla** [comment]
Tried the google drive link you posted earlier today. Appears to download but no change in settings.

**Comment by hvdwolf** [comment]
You also have this "2017-06-15" ROM. 
Maybe it is the strange behavior of those Joying 6.0.1 ROMs that "prevents" the installation. For other mods you sometimes also need multiple installs before it works.

**Comment by mikevanilla** [comment]
It worked after I did a reinstall of Joying then the standard Android. Thanks for putting the time into figuring it out, really do appreciate the help and this app. Separate issue but it appears the standard Bluetooth settings don't work as expected, but this Settings issue has been resolved for me.

**Comment by hvdwolf** [comment]
Good it works for you.
The bluetooth is indeed a separate issue. Please register that on XDA (https://forum.xda-developers.com/android-auto/android-head-units) or on the carjoying forum (forum.carjoying.com). The flaky bluetooth is a known issue and also depending on the phone used.

I leave this ticket somewhat longer open to see if @WallyDoodlez reacts. I'm also curious whether he has the same ROM or even another one.
